"""Generate docs/06_dax_measures.md from pbi_measures.py."""

from __future__ import annotations

from pathlib import Path

from pbi_measures import MEASURE_LIBRARY

DOC = Path(__file__).resolve().parent.parent / "docs" / "06_dax_measures.md"


def main() -> None:
    total = sum(len(ms) for _, ms in MEASURE_LIBRARY)
    L = [
        "# 06 — DAX Measure Library", "",
        "_Generated by `etl/gen_dax_doc.py` from `etl/pbi_measures.py`, which is also the "
        "source `etl/gen_semantic_model.py` writes into the `_Measures` table of the "
        "TMDL model._", "",
        f"**{total} measures** in **{len(MEASURE_LIBRARY)} display folders**. All monetary "
        "measures are USD (the reporting currency); `*_local` columns remain on detail "
        "tables. Sales measures exclude cancelled orders. Time intelligence runs on "
        "`dim_date[date]` (contiguous daily, auto date/time disabled).", "",
        "## Conventions", "",
        "| Suffix / prefix | Meaning |",
        "|---|---|",
        "| `(USD)` | Amount in US dollars (reporting currency) |",
        "| `(Rpt)` | Amount converted to the currency chosen in the *Reporting currency* slicer |",
        "| `PY` | Same measure, same-period-last-year |",
        "| `YoY` / `YoY %` | Current − PY, and that over PY |",
        "| `(Comparable Base)` | Restricted to markets live for the whole CY+PY span (US) — the like-for-like cut |",
        "| `(Expansion)` | Total − Comparable Base |",
        "",
        "## Key definitions", "",
        "- **Net Revenue** = Gross Revenue − Discounts − Returns  (`Gross Sales − Returns`).",
        "- **Gross Profit** = Net Revenue − COGS (moving-average cost). Returns reduce revenue "
        "by the refund; the COGS of restocked goods is not added back, so margin is a "
        "conservative estimate.",
        "- **Contribution Margin** = Gross Profit − Marketing Spend − Shipping Cost − Total Payment Cost.",
        "- **Cash Conversion Cycle** = DIO + DSO − DPO, from `fact_inventory_snapshot`, "
        "`fact_payment_schedule` and `fact_purchase_orders` respectively.",
        "",
        "---", "",
    ]
    for folder, measures in MEASURE_LIBRARY:
        L.append(f"## {folder}")
        L.append("")
        for m in measures:
            fmt = f"  ·  format `{m['format']}`" if m.get("format") else ""
            L.append(f"### `{m['name']}`{fmt}")
            L.append("")
            L.append("```dax")
            L.append(f"{m['name']} =")
            L.append(m["dax"].strip())
            L.append("```")
            L.append("")
        L.append("")
    DOC.write_text("\n".join(L), encoding="utf-8")
    print(f"wrote {DOC}  ({total} measures)")


if __name__ == "__main__":
    main()
